In [1]:
import json
import pandas as pd

In [2]:
pd.set_option('display.max_colwidth', None)
#pd.set_option('display.max_rows', -1) # doesn't seem to work in jupyterLab :(

In [3]:
with open('files/en.arberry_say.json') as f:
    arberry_sayings = json.load(f)

In [4]:
arberry_sayings_flattened = pd.json_normalize(arberry_sayings['data']['matches'])

In [5]:
arberry_sayings_flattened.columns = arberry_sayings_flattened.columns.str.replace('.', '_') # replace flattend colsnames' dots with underscores

In [6]:
arberry_sayings_flattened

,numberInSurah,number,text,edition_language,edition_englishName,edition_identifier,edition_name,edition_type,surah_englishNameTranslation,surah_number,surah_englishName,surah_revelationType,surah_name
0,8,15,"And some men there are who say, 'We believe in God and the Last Day'; but they are not believers.",en,A. J. Arberry,en.arberry,Arberry,translation,The Cow,2,Al-Baqara,Medinan,سورة البقرة
1,11,18,"When it is said to them, 'Do not corruption in the land', they say, 'We are only ones that put things right.'",en,A. J. Arberry,en.arberry,Arberry,translation,The Cow,2,Al-Baqara,Medinan,سورة البقرة
2,13,20,"When it is said to them, 'Believe as the people believe', they say, 'Shall we believe, as fools believe?' Truly, they are the foolish ones, but they do not know.",en,A. J. Arberry,en.arberry,Arberry,translation,The Cow,2,Al-Baqara,Medinan,سورة البقرة
3,14,21,"When they meet those who believe, they say, 'We believe'; but when they go privily to their Satans, they say, 'We are with you; we were only mocking.'",en,A. J. Arberry,en.arberry,Arberry,translation,The Cow,2,Al-Baqara,Medinan,سورة البقرة
4,25,32,"Give thou good tidings to those who believe and do deeds of righteousness, that for them await gardens underneath which rivers flow; whensoever they are provided with fruits therefrom they shall say, 'This is that wherewithal we were provided before'; that they shall be given in perfect semblance; and there for them shall be spouses purified; therein they shall dwell forever.",en,A. J. Arberry,en.arberry,Arberry,translation,The Cow,2,Al-Baqara,Medinan,سورة البقرة
...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,3,6141,"and Man says., 'What ails her?'",en,A. J. Arberry,en.arberry,Arberry,translation,The Earthquake,99,Az-Zalzala,Medinan,سورة الزلزلة
730,1,6208,"Say: 'O unbelievers,",en,A. J. Arberry,en.arberry,Arberry,translation,The Disbelievers,109,Al-Kaafiroon,Meccan,سورة الكافرون
731,1,6222,"Say: 'He is God, One,",en,A. J. Arberry,en.arberry,Arberry,translation,Sincerity,112,Al-Ikhlaas,Meccan,سورة الإخلاص
732,1,6226,Say: 'I take refuge with the Lord of the Daybreak,en,A. J. Arberry,en.arberry,Arberry,translation,The Dawn,113,Al-Falaq,Meccan,سورة الفلق
733,1,6231,"Say: 'I take refuge with the Lord of men,",en,A. J. Arberry,en.arberry,Arberry,translation,Mankind,114,An-Naas,Meccan,سورة الناس

In [7]:
arberry_sayings_flattened.shape[0] # get rowcount of df -- 734

734

In [8]:
theoretical_muhammad_pbuh_sayings = arberry_sayings_flattened.query('text.str.contains("Say: \'")')

In [9]:
theoretical_muhammad_pbuh_sayings.shape[0]

262

In [10]:
theoretical_muhammad_pbuh_sayings.columns

Index(['numberInSurah', 'number', 'text', 'edition_language',
       'edition_englishName', 'edition_identifier', 'edition_name',
       'edition_type', 'surah_englishNameTranslation', 'surah_number',
       'surah_englishName', 'surah_revelationType', 'surah_name'],
      dtype='object')

In [11]:
tmpbuhs_trimmed = theoretical_muhammad_pbuh_sayings[['edition_identifier', 'surah_englishName', 'surah_number', 'numberInSurah', 'text']]

In [12]:
tmpbuhs_trimmed # note that some sayings may cut across multiple ayahs, e.g. 3:26, 49:17. Need to investigate/handle.. in Arberry the quote beginning in 3:26 does not appear to reach any closing quote mark. :(

,edition_identifier,surah_englishName,surah_number,numberInSurah,text
13,en.arberry,Al-Baqara,2,80,"And they say, 'The Fire shall not touch us save a number of days.' Say: 'Have you taken with God a covenant? God will not fail in His covenant; or say you things against God of which you know nothing?"
15,en.arberry,Al-Baqara,2,91,"And when they were told, 'Believe in that God has sent down,' they said, 'We believe in what was sent down on us'; and they disbelieve in what is beyond that, yet it is the truth confirming what is with them. Say: 'Why then were you slaying the Prophets of God in former time, if you were believers?'"
16,en.arberry,Al-Baqara,2,93,"And when We took compact with you, and raised over you the Mount: 'Take forcefully what We have given you and give ear.' They said, 'We hear, and rebel'; and they were made to drink the Calf in their hearts for their unbelief. Say: 'Evil is the thing your faith bids you to, if you are believers.'"
17,en.arberry,Al-Baqara,2,94,"Say: 'If the Last Abode with God is yours exclusively, and not for other people, then long for death -- if you speak truly.'"
18,en.arberry,Al-Baqara,2,97,"Say: 'Whosoever is an enemy to Gabriel -- he it was that brought it down upon thy heart by the leave of God, confirming what was before it, and for a guidance and good tidings to the believers."
...,...,...,...,...,...
715,en.arberry,Al-Jinn,72,25,"Say: 'I do not know whether that which you are promised is nigh, or whether my Lord will appoint for it a space;"
730,en.arberry,Al-Kaafiroon,109,1,"Say: 'O unbelievers,"
731,en.arberry,Al-Ikhlaas,112,1,"Say: 'He is God, One,"
732,en.arberry,Al-Falaq,113,1,Say: 'I take refuge with the Lord of the Daybreak
733,en.arberry,An-Naas,114,1,"Say: 'I take refuge with the Lord of men,"

In [13]:
tmpbuhs_trimmed.to_csv('files/tmpbuhs_trimmed_')